@startuml

class Admin{
+ Admin(String username, String password, String name)
# addMedia(Movie movie)
# addMedia(Series serie)
# removeMedia(String title)
# changeMedia(String oldTitle, String newTitle)
# addAdmin(Account newAdmin)
}

class StreamingService{
- TextUI ui
- MediaManager manager
+ StreamingService(Account account)
+ void showMenu()
+ void search()
- void searchTitle(String title)
- void searchCategory(String categoryName)
- void searchByYear(int startYear, int endYear)
- void searchByRating(double rating)
- void displayMedia()
+ void showSeenMedia(Account a)
+ void showSavedMedia(Account a)
+ void logOut()
+ void endStreamingService()
}

class Main{
- Login start
 + static void main(String[] args)
}

class Movie{
- int year
+ Movie(String title, int year, List<String> genre, double rating)
+ String toString()
+ String getTitle()
+ int getYear()
+ List<String> genre getGenre()
+ double getRating()
}

class Series{
- List <String> yearSpan
- List <int> episodes
- List <List> seasons
+ Series(String title, List<String> releaseYear,List<String> genre, double rating, List<String> seasons)
}

class MediaManager {
- FileIO io
- ArrayList<Media> media
+ MediaManager(String moviesPath, String seriesPath)
+ void loadMovieData()
+ void loadSeriesData()
+ void saveMediaData()
+ ArrayList<Media> media getMedia()
}

class Login {
- TextUI ui
- AccountManager manager
- StreamingService service
+ Login(String appName)
- void start()
- void login()
}

Abstract Media{
- String title
- List<String> genre
- double rating
+Media(String title, List<String> genre, double rating)
}

class Account{
- String name
- String username
- String password
- LocalDate birthday
- int age
- boolean isChild
+ Account(String username, String password, String name, LocalDate birthday)
- int convertAge(LocalDate date)
+ Account getUsername()
+ void setUsername(String newUsername)
+ void setPassword(String oldPassword, String newPassword)
+ String getName()
+ int getAge()
}


class AccountManager {
- FileIO io
- ArrayList<Account>
+ AccountManager(String path)
+ void createAccount()
+ void loadUserData()
+ void saveUserData()
+ boolean isUserInSystem(String username)
+ boolean isUserNameAndPasswordCorrect()
+ boolean isUserAdmin(User u)
}

package "util" {
    class TextUI {
    - Scanner scan
    + boolean promptBinary(String msg)
    + String promptText(String msg)
    + int promptNumeric(String msg)
    + ArrayList<String> promptChoice(ArrayList<String> options, int limit, String msg)
    + void displayMessage(String msg)
    + void displayList(ArrayList<String> list, String msg)
    }
}

package "util" {
    class FileIO{
    + void saveData(ArrayList<String> data, String path, String header)
    + ArrayList<String> readData(String path)
    + String[] readData(String path, int length)
    }
 }

interface MediaPlayer {
+ playMedia()
+ stopMedia()
}

Main *-- Login
Login *-- AccountManager
Login *-- StreamingService
StreamingService *-- Account

MediaPlayer <|.. Movie
MediaPlayer <|.. Series
AccountManager *-- Account
AccountManager *-- FileIO
Login *-- TextUI
StreamingService *-- TextUI

StreamingService *-- MediaManager
MediaManager *-- FileIO
MediaManager *-- Media
Account <|-- Admin

Media <|-- Movie
Media <|-- Series

@enduml